version: '2'  
services:  
  nginx:
    image: nginx:latest
    ports:
      - "8888:8000"
    volumes:
      - .:/code
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    command: bash -c "pip install -r requirements.txt && python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn hosting_web_interface.wsgi:application -b 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - .:/code
    expose:
      - "8000"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: pgsuperuser
      POSTGRES_PASSWORD: pgsuperuserpassword

