version: '2'  
services:  
  nginx:
    image: nginx:latest
    ports:
      - "8000"
    volumes:
      - .:/code
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn {{ wsgi_app_name }} -b 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - .:/code
    expose:
      - "8000"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: pgsuperuser
      POSTGRES_PASSWORD: pgsuperuserpassword


# probably should collect static as well:
# docker exec webinterface_web_1 /bin/sh -c "python manage.py collectstatic --noinput"

# {{ wsgi_app_name }} is to look like hosting_web_interface.wsgi:application
