# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 18:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import frontend.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('db_user', models.CharField(max_length=128, unique=True)),
                ('db_pass', models.CharField(max_length=128)),
                ('repo_url', models.CharField(max_length=4096)),
                ('app_type', models.CharField(max_length=128)),
                ('app_path', models.CharField(max_length=4096, null=True)),
                ('app_url', models.CharField(max_length=4096, null=True)),
                ('desired_state', models.CharField(default=frontend.models.AppStates('disabled'), max_length=128)),
                ('current_state', models.CharField(max_length=128, null=True)),
                ('image_id', models.CharField(max_length=4096, null=True)),
                ('container_id', models.CharField(max_length=4096, null=True)),
                ('restart_required', models.BooleanField(default=False)),
                ('deploy_required', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
