# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import frontend.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20170208_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_uploaded', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='app',
            name='desired_state',
            field=models.CharField(default=frontend.models.AppStates('first_run_waiting'), max_length=128),
        ),
        migrations.AddField(
            model_name='logrequest',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_requests', to='frontend.App', unique=True),
        ),
    ]
