# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20170217_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=4096)),
                ('received_at', models.DateTimeField(auto_now=True)),
                ('app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='frontend.App')),
            ],
        ),
    ]
