# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.App'),
        ),
    ]
